{
 "title": "SmartCitizen Device details",
 "tags": [
  "smartcitizen",
  "device",
  "sensors"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "name of selected device",
    "query": "label_values(smartcitizen_device_info,uuid)"
   }
  ]
 },
 "panels": [
  {
   "title": "Device Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device Details",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "group by (name, uuid, description) (smartcitizen_device_info{uuid=~\"$device\"})"
      }
     ]
    },
    {
     "title": "Device Alerts",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "group by (alertname,alertstate,severity) (ALERTS{device=~\"$device\"})"
      }
     ]
    },
    {
     "title": "Battery Level",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "smartcitizen_sensor_device_battery{device=~\"$device\"}"
      }
     ]
    },
    {
     "title": "WiFi Signal Strength",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "smartcitizen_sensor_device_rssi{device=~\"$device\"}"
      }
     ]
    },
    {
     "title": "Data ",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
     "targets": [
      {
       "expr": "smartcitizen_device_state_has_published{device=~\"$device\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "environment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "smartcitizen_sensor_environment_temperature{device=~\"$device\"}"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
     "targets": [
      {
       "expr": "smartcitizen_sensor_environment_humidity{device=~\"$device\"}"
      }
     ]
    },
    {
     "title": "Barometric Pressure",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
     "targets": [
      {
       "expr": "smartcitizen_sensor_environment_barometric_pressure{device=~\"$device\"}"
      }
     ]
    },
    {
     "title": "Weighted Noise Level",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "smartcitizen_sensor_environment_weighted_noise_level{device=~\"$device\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "light",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ambient Light",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "smartcitizen_sensor_environment_ambient_light{device=~\"$device\"}"
      }
     ]
    },
    {
     "title": "UVA",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
     "targets": [
      {
       "expr": "smartcitizen_sensor_environment_uva{device=~\"$device\"}"
      }
     ]
    },
    {
     "title": "UVB",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
     "targets": [
      {
       "expr": "smartcitizen_sensor_environment_uvb{device=~\"$device\"}"
      }
     ]
    },
    {
     "title": "UVC",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "smartcitizen_sensor_environment_uvc{device=~\"$device\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "air_quality",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "PM1.0",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "smartcitizen_sensor_environment_pm1{device=~\"$device\"}"
      }
     ]
    },
    {
     "title": "PM2.5",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
     "targets": [
      {
       "expr": "smartcitizen_sensor_environment_pm2_5{device=~\"$device\"}"
      }
     ]
    },
    {
     "title": "PM4.0",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
     "targets": [
      {
       "expr": "smartcitizen_sensor_environment_pm4{device=~\"$device\"}"
      }
     ]
    },
    {
     "title": "PM10",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "smartcitizen_sensor_environment_pm10{device=~\"$device\"}"
      }
     ]
    },
    {
     "title": "Total Particle Score (TPS)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
     "targets": [
      {
       "expr": "smartcitizen_sensor_environment_tps{device=~\"$device\"}"
      }
     ]
    },
    {
     "title": "PN0.5",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
     "targets": [
      {
       "expr": "smartcitizen_sensor_environment_pn0_5{device=~\"$device\"}"
      }
     ]
    },
    {
     "title": "PN1.0",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "smartcitizen_sensor_environment_pn1{device=~\"$device\"}"
      }
     ]
    },
    {
     "title": "PN2.5",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 52 },
     "targets": [
      {
       "expr": "smartcitizen_sensor_environment_pn2_5{device=~\"$device\"}"
      }
     ]
    },
    {
     "title": "PN4.0",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 52 },
     "targets": [
      {
       "expr": "smartcitizen_sensor_environment_pn4{device=~\"$device\"}"
      }
     ]
    },
    {
     "title": "PN10.0",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "smartcitizen_sensor_environment_pn10{device=~\"$device\"}"
      }
     ]
    }
   ]
  }
 ]
}