# yamllint configuration
# See https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  # Line length - be more lenient for documentation and complex configs
  line-length:
    max: 120
    level: warning

  # Indentation - standard 2 spaces
  indentation:
    spaces: 2
    indent-sequences: true

  # Comments - allow flexibility in comment formatting
  comments:
    min-spaces-from-content: 1

  # Document start - not required for all files
  document-start:
    present: false

  # Trailing spaces - error level
  trailing-spaces: enable

  # Empty lines - allow some flexibility
  empty-lines:
    max: 2

  # Brackets and braces - warning level for better readability
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Truthy values - allow yes/no/on/off for better readability
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

# Ignore generated or third-party files
ignore: |
  .github/
  vendor/
  node_modules/
  helm/templates/
