# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!
  DOCKER_BIN: nerdctl
  DOCKER_HOST: docker.io

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  "release:helm":
    cmds:
      - helm package helm --app-version "{{.VERSION}}"
      - helm push scmprober-*.tgz oci://registry-1.docker.io/tauho
      - rm scmprober-*.tgz
    vars:
      VERSION:
        sh: "cat VERSION"

  "release:docker":
    cmds:
      - "{{.DOCKER_BIN}} tag scmprober:latest {{.DOCKER_HOST}}/tauho/scmprober:latest"
      - "{{.DOCKER_BIN}} push {{.DOCKER_HOST}}/tauho/scmprober:{{.VERSION}}"
      - "{{.DOCKER_BIN}} tag scmprober:latest {{.DOCKER_HOST}}/tauho/scmprober:{{.VERSION}}"
      - "{{.DOCKER_BIN}} push {{.DOCKER_HOST}}/tauho/scmprober:{{.VERSION}}"
    vars:
      VERSION:
        sh: "cat VERSION"

  release:
    cmds:
      - task release:docker
      - task release:helm

  "build:docker":
    cmds:
      - "{{.DOCKER_BIN}} build -t scmprober:latest -f Dockerfile ."

  "run:docker":
    cmds:
      - "mkdir -p config secrets"
      - "{{.DOCKER_BIN}} run --rm --volume {{.PWD}}/config:/app/config:ro --volume {{.PWD}}/secrets:/app/secrets:ro scmprober:latest"
    deps:
      - build:docker
