# https://taskfile.dev

version: "3"

dotenv: [".env"]

vars:
  GREETING: Hello, World!
  DOCKER_BIN: nerdctl
  DOCKER_HOST: docker.io
  SMC_NAMESPACE: smcprober

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  "test:alerts":
    cmds:
      - echo "Running alert tests for SmartCitizen device low battery..."
      - promtool test rules tests/alerts/test_*.yaml

  "generate:device:dashboard":
    cmds:
      - echo "Generating SmartCitizen Device Dashboard..."
      - |
        go run cmd/gen-device-dashboard/main.go \
          --config configs/device-dashboard.json \
          > helm/dashboards/device-details.json
  "generate:dashboards":
    cmds:
      - task: generate:device:dashboard

  "release:helm":
    cmds:
      - task: generate:dashboards
      - helm package helm --app-version "{{.VERSION}}"
      - helm push smcprober-*.tgz oci://registry-1.docker.io/tauho
      - rm smcprober-*.tgz
    vars:
      VERSION:
        sh: "cat VERSION"

  "run:exporter":
    cmds:
      - "echo Starting SmartCitizen Exporter..."
      - |
        go run cmd/smcexporter/main.go \
          --config configs/config-exporter-dev.json \
          --dotenv .env

  "run:job":
    cmds:
      - echo "Trigger ProbeJob"
      - go run cmd/smcjob/main.go --config configs/config.json --dotenv .env

  "run:downloader":
    cmds:
      - echo "Fetching data from SmartCitizen API..."
      - go run cmd/smcdownload/main.go --config configs/config.json --dotenv .env

  lint:
    desc: Run golangci-lint to check code quality
    cmds:
      - golangci-lint run ./...

  "lint:fix":
    desc: Run golangci-lint and automatically fix issues
    cmds:
      - golangci-lint run --fix ./...

  "template:helm":
    cmds:
      - |
        helm template dev ./helm --debug \
          --namespace {{.SMC_NAMESPACE}} \
          --set "imagePullSecrets[0].name"="smcprober-registry" \
          --set-file=configJSON=configs/config-k8s.json \
          --set-file=configExporterJSON=configs/config-exporter-k8s.json \
          --set-file=secret.env=.env \
          --set serviceMonitor.enabled=true \
          --set alertmanager.enabled=true \
          --set alertmanager.webhooks.default="{{.NTFY_DEFAULT_WEBHOOK_URL}}" \
          --set alertmanager.webhooks.critical="{{.NTFY_CRITICAL_WEBHOOK_URL}}" \
          > smcprober.yaml
      - kubectl apply -f smcprober.yaml --dry-run=server

  "build:docker":
    cmds:
      - "{{.DOCKER_BIN}} build -t smcprober:latest -f Dockerfile ."

  "run:docker":
    cmds:
      - "mkdir -p configs secrets"
      - |
        {{.DOCKER_BIN}} run --rm \
          --volume {{.PWD}}/configs:/app/configs:ro \
          --volume {{.PWD}}/secrets:/app/secrets:ro \
          -p 8080:8080 \
          smcprober:latest \
          /app/smcexporter --config /app/configs/config-k8s.json --dotenv /app/secrets/.env
    deps:
      - build:docker

  "release:docker":
    cmds:
      - task: "build:docker"
      - "{{.DOCKER_BIN}} tag smcprober:latest {{.DOCKER_HOST}}/tauho/smcprober:latest"
      - "{{.DOCKER_BIN}} push {{.DOCKER_HOST}}/tauho/smcprober:latest"
      - "{{.DOCKER_BIN}} tag smcprober:latest {{.DOCKER_HOST}}/tauho/smcprober:{{.VERSION}}"
      - "{{.DOCKER_BIN}} push {{.DOCKER_HOST}}/tauho/smcprober:{{.VERSION}}"
    vars:
      VERSION:
        sh: "cat VERSION"

  release:
    cmds:
      - task: release:docker
      - task: release:helm

  "deploy:namespace":
    cmds:
      - kubectl create namespace {{.SMC_NAMESPACE}} --dry-run=server -o yaml | kubectl apply -f -

  "deploy:credentials":
    cmds:
      - echo "Creating Docker registry secret in namespace {{.SMC_NAMESPACE}}"
      - |
        kubectl create secret docker-registry smcprober-registry -n {{.SMC_NAMESPACE}} \
          --docker-username={{.DOCKER_USERNAME}} \
          --docker-password={{.DOCKER_PASSWORD}} \
          --docker-server={{.DOCKER_HOST}}
    requires:
      vars: [DOCKER_USERNAME, DOCKER_PASSWORD, DOCKER_HOST]
  "expose:prometheus":
    cmds:
      - "kubectl port-forward -n monitoring svc/prometheus-operated 9090:9090"
  "expose:grafana":
    cmds:
      - "kubectl port-forward -n monitoring svc/prometheus-grafana 3000:80"
  "expose:service":
    cmds:
      - "kubectl port-forward -n {{.SMC_NAMESPACE}} svc/dev-smcprober 8080:80"
