apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-webhook-funnel
  namespace: smc-cicd
  annotations:
    tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: el-github-webhook
                port:
                  number: 8080
